### ISSUE TITLE
Huggingface Spaces

### ISSUE THREAD

**Issue by AK391** [naver/fire#1]
Hi, would you be interested in sharing a web demo on Huggingface Spaces for fire?

It would make this model more accessible as it would allow people to try out the model directly from the browser. Some other recent machine learning model repos have set up Spaces for easy access:

github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/akhaliq/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

Spaces is completely free, and I can help setup a Gradio Space. Here are some getting started instructions if you'd prefer to do it yourself: https://huggingface.co/blog/gradio-spaces

**Comment by skamalas** [comment]
Thanks for reaching out @AK391  (and sorry for a late reply, things are busy with upcoming deadlines :)

This is a great idea and we are really interested in this, thanks for suggesting! We have no bandwidth from our side for this before early March, but eager to look into this around that time.

So, how about we touch base around then?

Some first questions, to understand the feasibility:
* FIRe/LIT is primarily a retrieval method - do Huggingface Spaces support retireval demos? I.e. this would imply having a (small/demo) database to query, with features for retrieval + images for visualization. 
* (From your side) can we use/upload public datasets for a Huggingface Space demo (eg ROxford)?

**Comment by skamalas** [comment]
We made a HF Spaces demo showcasing super-feature matching here:
https://huggingface.co/spaces/naver/SuperFeatures

Thanks again for suggesting! Closing this issue

**Comment by AK391** [comment]
@skamalas thanks for making the gradio demo, datasets can be uploaded to user profiles or organizations, see guide here: https://huggingface.co/docs/datasets/upload_dataset.html
